// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/14fe4313f4a1cf69add3505a2ab1dbc690dc2116/ng-cordova/toast.d.ts
declare namespace ngCordova {

	interface IToastService {

		showShortTop(message:string):angular.IPromise<any>;
		showShortCenter(message:string):angular.IPromise<any>;
		showShortBottom(message:string):angular.IPromise<any>;

	  	showLongTop(message:string):angular.IPromise<any>;
		showLongCenter(message:string):angular.IPromise<any>;
		showLongBottom(message:string):angular.IPromise<any>;

	  	show(message:string, duration:string, position:string):angular.IPromise<any>;
	}
}
