// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/14fe4313f4a1cf69add3505a2ab1dbc690dc2116/ng-cordova/dialogs.d.ts
declare namespace ngCordova {

  export interface IDialogsPromptResult {
        input1: string;
        buttonIndex: number;
    }

    export interface IDialogsService {
        alert(message: string, title?: string, buttonName?: string): ng.IPromise<void>;
        confirm(message: string, title?: string, buttonArray?: Array<string>): ng.IPromise<number>;
        prompt(message: string, title?: string, buttonArray?: Array<string>, defaultText?: string): ng.IPromise<IDialogsPromptResult>;
        beep(repetitions: number): void;
    }

}
